name=TestLib
version=0.1.0
author=Daniele Aimo (d.aimo@arduino.cc)
maintainer=Arduino <info@arduino.cc>
sentence=Library used to perform tests 
paragraph=A set of common functions useful for test purpose
category=Test
url=https://github.com/maidnl/ATestLib
architectures=*
includes=atestlib.h

