CONFIG_GPIO=y
CONFIG_PRINTK=y

# Enable USB Stack
CONFIG_USB_DEVICE_STACK=y
CONFIG_USB_DEVICE_PRODUCT="Arduino Giga Hello"

# Use USB CDC ACM for console
CONFIG_SERIAL=y
CONFIG_CONSOLE=y
CONFIG_UART_CONSOLE=y
CONFIG_UART_LINE_CTRL=y
CONFIG_USB_DEVICE_INITIALIZE_AT_BOOT=n

CONFIG_SPI=y
CONFIG_SPI_ASYNC=y
CONFIG_SPI_SLAVE=y
CONFIG_LOG=y
CONFIG_SPI_STM32_INTERRUPT=y
CONFIG_DMA=y

# Enable the specific STM32 SPI DMA driver
CONFIG_SPI_STM32_DMA=y

# Enable Cache Management for Cortex-M7 DMA coherence
CONFIG_CACHE_MANAGEMENT=y
